### ISSUE TITLE
Chore: Community site - Move claim database from MySQL to Postgres

### ISSUE THREAD

**Issue by rattrap** [Taraxa-project/taraxa-platform#114]
Right now we're using a MySQL data for the claim backend. All other community site apps use a Postgres db. We should migrate the claim backend to Postgres as well.

**Comment by VargaElod23** [comment]
@rattrap  What do you think about trying this one out: https://cloud.google.com/blog/products/databases/database-cloud-migrations-made-easy-for-postgresql-mysql ?

**Comment by VargaElod23** [comment]
Ofc. I already modified the compose file to see, bot I'll need to test it in the late afternoon. 👍🏼
