### ISSUE TITLE
Bug: Community Site - Delegation: Node status shows as inactive for all nodes

### ISSUE THREAD

**Issue by VargaElod23** [Taraxa-project/taraxa-platform#125]
# Issue

One of our super-star node runners said that all the nodes are showing up as inactive on the community site - he says they are indeed active, so probably an issue with the site. Here are his screen shots.
![image](https://user-images.githubusercontent.com/100562086/161697839-82fc22c7-bc0f-46c8-85aa-4b21e41a9bfa.png)

## Date captured

05.04.2022.

**Comment by rattrap** [comment]
Explorer was stuck. Was not syncing PBFT blocks - https://explorer.mainnet.taraxa.io/
I restarted it. The community site should also show the online nodes.
