### ISSUE TITLE
Feature: Community site - Claim popup

### ISSUE THREAD

**Issue by rattrap** [Taraxa-project/taraxa-platform#143]
https://www.figma.com/file/PdAFhWcrpYnUAaFA2UIlH8/TARAXA-Community?node-id=2305%3A27310

<img width="265" alt="popup" src="https://user-images.githubusercontent.com/3051409/166253444-b40a8512-5862-456e-bdce-db3e149e2ec2.png">

<img width="177" alt="status" src="https://user-images.githubusercontent.com/3051409/166253542-9c21f864-10a2-4725-8d15-e5c7614c707a.png">

**Comment by VargaElod23** [comment]
Style:

![Image](https://user-images.githubusercontent.com/100562086/166482396-b2dc5b9b-615e-4885-9bfe-867de396749b.png)
