### ISSUE TITLE
Community site - My profile - My rewards

### ISSUE THREAD

**Issue by CooperNic** [Taraxa-project/taraxa-platform#148]
There is a wrong value of my rewards - 25,095,940,000,000,000,000,000
Should be 35,095.87

![image](https://user-images.githubusercontent.com/55191300/166947777-3dfb23b1-05a6-4aed-b873-79cb7827ecf3.png)

**Comment by rattrap** [comment]
Fixed in https://github.com/Taraxa-project/taraxa-platform/commit/d9543802d1a0042d87e5ce4aed8bfb2f30a8f668
