### ISSUE TITLE
[Explorer] Research graph library for Dag Blocks page

### ISSUE THREAD

**Issue by Malak67** [Taraxa-project/taraxa-platform#248]
We need some library recomendation to implement this:
https://www.figma.com/file/4VZkpJXg5KyC1t2BvOEU1u/Main-page?node-id=0%3A1

![Image](https://user-images.githubusercontent.com/9773044/192550732-3a972565-f974-437c-98f0-8d14030e15bc.png)

The design is not yet ready but the boxes will be connected to eachother similar with the one in the old Explorer.

**Comment by farebord** [comment]
@VargaElod23 
React Flow - https://reactflow.dev/docs/examples/nodes/custom-node/
