### ISSUE TITLE
[Explorer Indexer] Import all genesis balances as fake transactions

### ISSUE THREAD

**Issue by VargaElod23** [Taraxa-project/taraxa-platform#354]

**Comment by rattrap** [comment]
New config: `curl -s -X POST -H 'Content-Type: application/json' -d '{"jsonrpc":"2.0","method":"taraxa_getConfig","params": [],"id":1}' https://rpc.testnet.taraxa.io | jq .result.initial_balances`

Old config (mainnet): `curl -s -X POST -H 'Content-Type: application/json' -d '{"jsonrpc":"2.0","method":"taraxa_getConfig","params": [],"id":1}' https://rpc.testnet.taraxa.io | jq .result.final_chain.state.genesis_balances`

**Comment by VargaElod23** [comment]
- [ ] Add a new get on root for all modules that returns all the endpoint data in a json
