### ISSUE TITLE
[Community site - DPOS] Delegation page

### ISSUE THREAD

**Issue by rattrap** [Taraxa-project/taraxa-platform#385]
Page: https://qa.community.taraxa.io/delegation
DPOS contract interface: https://github.com/Taraxa-project/taraxa-evm/blob/master/taraxa/state/dpos/solidity/dpos_contract_interface.sol

1. gets all of the data from the DPOS contract for the delegators list
2. delegate/undelegate should work by calling the contract functions
3. add redelegate functionality
3.1. The staking page (https://community.taraxa.io/staking) and the delegation page should be merged
- My Validators - number of validators I delegated to
- My Delegated TARA - total number of delegated tokens
- Undelegated TARA - TARA that's in the contract and can be reDelegated (each row will have a new re-delegate button)
These should only show up if you are connected to your Metamask wallet and on the right network
3.2. Switch network notice - If you are not on the right network, you should see the switch network notice + button.
3.3. Only show my validators switch

**Comment by VargaElod23** [comment]
Changes:

- Undelegated TARA - TARA that's in the contract and can be reDelegated (each row will have a new re-delegate button) -> TARA that is awaiting release from delegation and can be claimed or canceled.
- Enable re-delegate button if a user has at least one active delegation.
- Always display undelegation requests -> display a cancel button if unclaimable, both claim and cancel if claimable.
- Change re-delegate modal to support a dropdown of addresses that the user can delegate to.
- Change re-delegate logic to move the user's active delegation for the chosen amount from the validator that he clicked the re-delegate button on to the chosen address.
