### ISSUE TITLE
[Community site - DPOS] Nodes page

### ISSUE THREAD

**Issue by rattrap** [Taraxa-project/taraxa-platform#386]
Page: https://qa.community.taraxa.io/node
DPOS: https://github.com/Taraxa-project/taraxa-evm/blob/master/taraxa/state/dpos/solidity/dpos_contract_interface.sol#L176

1. Testnet tab - Remains the same. We only change the functionality under the Mainnet tab
2. Switch network notice - If you are not on the right network, you should see the switch network notice + button + the "Register node" button will be disabled
3. The register a node popup will call the contract method and send the minimum of 1000 TARA
4. Display the list of my validators using the `getValidatorsFor` contract method
5. Edit page that lets you modify the decription and endpoint of validators using the `setValidatorInfo` contract method

![Image](https://user-images.githubusercontent.com/3051409/219653925-da840612-0e3d-4da8-829b-e09caa3ea088.png)

**Comment by rattrap** [comment]
Don't have `4. Display the list of my validators using the getValidatorsFor contract method`

**Comment by Malak67** [comment]
We have this method in the RunValidator.tsx file, line 130 (const myValidators = await getValidatorsFor(account);) this method calles the mainnetDpos!.getValidatorsFor from useValidators.tsx file, line 97
