### ISSUE TITLE
[Community site - DPOS] Indexer

### ISSUE THREAD

**Issue by rattrap** [Taraxa-project/taraxa-platform#388]
DPOS: https://github.com/Taraxa-project/taraxa-evm/blob/master/taraxa/state/dpos/solidity/dpos_contract_interface.sol#L176

Create new subgraph and index all of the events from the DPOS contract.

First thing that we need is the delegations/undelegation events and to have a list of current delegations for each validator

**Comment by VargaElod23** [comment]
Current mainnet has no eth-like events enabled yes for the DPOS contract.

**Comment by VargaElod23** [comment]
Also testnet and devnet has an error that the DPOS contract logs are logged to the zero address. Once that's fixed we can test the indexing on one of them.

**Comment by VargaElod23** [comment]
Blocked until https://github.com/graphprotocol/graph-tooling/issues/1188 is resolved
