### ISSUE TITLE
Fix: Community site - Staking page - Add latest design changes

### ISSUE THREAD

**Issue by rattrap** [Taraxa-project/taraxa-platform#44]
A couple of boxes are missing from the community site that are included in the latest design: 

- TARA rewards -> Lifetime staking rewards
- Validators delegated
- Un-Delegated stake
- Last week’ annualized staking yield

We should change the way we let users know that they SHOULD delegate: right now it’s “Delegate” box with staked un-delegated TARA, that says “you must delegate...” and a button “Delegate to validators” that redirects users to Delegation page.

There’s a couple of reasons why we should update this. Most importantly - this box might confuse people cause we use this kind of box only for action with tokens and NOT for redirecting users to somewhere else.
More appropriate for this purposes would be adding a notice to the top.

https://community.taraxa.io/staking

![image](https://user-images.githubusercontent.com/3051409/153221766-2de1bb8e-aa70-4c66-a93a-d811d355a060.png)

**Comment by farebord** [comment]
I couldn't find a way to show a title to the button if disabled.

**Comment by farebord** [comment]
Please provide tooltip information for each new box (the exclamation icon on the right of each box)

**Comment by VargaElod23** [comment]
@rattrap Please provide:

- Information about the endpoints that need to be called for the undelegated/delegated information.
- Description of the tooltips.

**Comment by rattrap** [comment]
### Lifetime staking yield
Data: the same value we have now in TARA rewards, we just remove the redeem button
Tooltip: Total number of TARA staking rewards earned for the lifetime of the connected wallet.

### My staked TARA
Data: same value
Tooltip: Total number of TARA currently staked in the staking contract for connected wallet.

### Validators delegated
Data:
1. For the number of delegators we can get it by calling `https://api-delegation.community.taraxa.io/validators?show_fully_delegated=true&show_my_validators=true`
2. If the number is of delegators is zero, the button should be disabled
3. If the number is greater than zero, when you click the button it takes you to the delegation section (https://community.taraxa.io/delegation) with the "Only show my validators" switch turned on (we also need to implement that)
Tooltip: Number of validators you delegated TARA to.

### Lifetime annualized staking yield
Data: 20% static value. The same as we have now in the "Anualized yield" box
Tooltip: Effective annualized yield, this could be different than the stated expected yields due to special community events.

### Un-delegated stake
Data: The value in the "My staked TARA" box minus the sum of the ownDelegation field from all the delegators returned by the following API: `https://api-delegation.community.taraxa.io/validators?show_fully_delegated=true&show_my_validators=true` (same API as for Validators delegated box)
Tooltip: Total number of TARA staked currently that weren't delegated to any validators.

### Last weeks' annualized staking yield
Data: None. Let's just remove it for now

### Stake
Data: Same as we have now for the "Available to Stake" box.
Tooltip: Total number of TARA currently in the connected wallet that could be staked.

### Delegate
Data:
1. Same value as the "Un-delegated stake" box
2. If the value === 0, we disabled the button
3. if the value > 0, on click it should redirect the user to the delegation section (https://community.taraxa.io/delegation)
Tooltip: Total number of TARA staked currently that aren't earning any yield.
