### ISSUE TITLE
[Explorer] Cleanup

### ISSUE THREAD

**Issue by Malak67** [Taraxa-project/taraxa-platform#469]

**Comment by Malak67** [comment]
@rattrap Besides the cleanup you mentioned that we need to fix some other issues:
1. Transactions are not refetched for Address details (can you give me the addresses where I can replicate this?)
2. Display Wei or Tara based on a certain threshold (what is the threshold?)

**Comment by rattrap** [comment]
1. https://mainnet.explorer.taraxa.io/address/0xf3b803a8f4c4fc3fbe454b6438dc0ed22735f01b - click on a "to" address and then refresh + back
2. If >1000 Wei, display in TARA
    If <= 1000 Wei, display in Wei

Just for the value in the tx, not for the gas

**Comment by rattrap** [comment]
4. Gas Limit / Gas used - We don't show the gas limit, just the gas used. Add gas limit after gas used:


```
GAS USED / GAS LIMIT: 21000 / 30000
```
