### ISSUE TITLE
Fix: Community site - UI - Validators page - Add divider

### ISSUE THREAD

**Issue by rattrap** [Taraxa-project/taraxa-platform#49]
Fully delegated nodes in validators list (delegation page) - no divider line.
Right now fully delegated nodes list doesn’t look distinctive enough.
We should add a green divider line and green text “fully delegated”.

https://community.taraxa.io/delegation

![Validators](https://user-images.githubusercontent.com/3051409/153226017-2e5314d0-4e6b-4911-8f7d-a2d7a961d236.png)

**Comment by farebord** [comment]
We can mar this as done. Am I right? @rattrap
