### ISSUE TITLE
Fix: Community site - UI - Validators page - Delegation popup spacing

### ISSUE THREAD

**Issue by rattrap** [Taraxa-project/taraxa-platform#50]
“delegate to...” popup spacings are too narrow. Check latest design.

![Delegate to...](https://user-images.githubusercontent.com/3051409/153226546-07615b02-d21d-4ee8-973f-368a8590b501.png)

**Comment by farebord** [comment]
This is an old issue. Although is not pixel perfect it closer to the design than the old screenshot.

## How its looking now
<img width="792" alt="imagen" src="https://user-images.githubusercontent.com/602693/163441197-9101d7ea-a562-4173-bdfb-aae0cb5cf781.png">

**Comment by rattrap** [comment]
Let's add the Node Icon next to the title.
