### ISSUE TITLE
Fix: Community site - UI - Validators page - Commission change warning

### ISSUE THREAD

**Issue by rattrap** [Taraxa-project/taraxa-platform#52]
The commission change warning (orange icon) is not centered horizontally with the commission value (percentage).

![Commission Warning](https://user-images.githubusercontent.com/3051409/153227580-987f27b7-6717-48fb-9c21-382faf609bad.png)

**Comment by farebord** [comment]
Already fixed.
<img width="295" alt="imagen" src="https://user-images.githubusercontent.com/602693/164775164-c16e39fa-0acc-4e66-89aa-96dd8aa322b1.png">
