### ISSUE TITLE
[Explorer] Add support for event logs

### ISSUE THREAD

**Issue by rattrap** [Taraxa-project/taraxa-platform#531]
Similar to https://etherscan.io/tx/0xe9c162c8b263e0188704d9f3790022c38b22418e3afc3275af7c19a099d064bb#eventlog

- New table in Transaction page (https://mainnet.explorer.taraxa.io/tx/0xf492750a5d51ff6a1a2566ac12133ae041486b6617d92c38646de9e6b22ba2f4) like the the other tables in the explorer (example https://mainnet.explorer.taraxa.io/block/0x8e085a8449585294136fe4aa4f65ddafa2347f65ebdbcba7e10d98099c11e38c)

## Data to Display:
1. Address
2. Name
3. Params

## API Call Requirements
- No pagination
- We don't do the request if the transaction is not a contract call of contract creation

## Response data layout
https://github.com/Taraxa-project/taraxa-indexer/pull/97#issue-1793488536

![Event Logs](https://github.com/Taraxa-project/taraxa-platform/assets/3051409/eb51c0a1-f8cb-4d83-9454-331fbe792f49)

**Comment by EvolOfThings** [comment]
hello! Can I pick up this task?

**Comment by VargaElod23** [comment]
Hi @EvolOfThings ! Nice to have you here 😃. Can you hit me up somewhere on Discord or Telegram to discuss about contributing?
