### ISSUE TITLE
Feature: Community site - Bounties - Improvements

### ISSUE THREAD

**Issue by rattrap** [Taraxa-project/taraxa-platform#56]
On the bounty details page - looks like username & address (or is it a hash?) in 1 line (as it is now) makes the bounty card too wide on the screen and it goes beyond the header. We can change the display of the addresses of the bounty submissions (1 line for username and 1 line for address). Or even better - shorten the number of hash symbols.

https://user-images.githubusercontent.com/3051409/153231730-bc7b6866-97cb-43b0-b8be-da91d42a86ff.mov

**Comment by farebord** [comment]
This happens in a lot of pages with fixed-width boxes. We can add media queries to render them in vertical order if less than 1000px. Will that be okey? @rattrap

**Comment by rattrap** [comment]
I don't think that's the problem here. The text on the left side should just wrap in its current width.

**Comment by rattrap** [comment]
Let's use the same trim functionality that we use for addresses.



![trim](https://user-images.githubusercontent.com/3051409/166254892-c7794743-7cee-4130-bce4-427f43e82dd6.png)
