### ISSUE TITLE
[Community site] Don't show commission changed icon if validator is new

### ISSUE THREAD

**Issue by rattrap** [Taraxa-project/taraxa-platform#572]
Right now we show the commission changed icon (notification) for new validators. It should only be displayed for validators that changed their commission apart from the initial one.

We can use the `last_commission_change` value in the validator to check if it's a commission change or the node was just created.

https://github.com/Taraxa-project/taraxa-evm/blob/master/taraxa/state/dpos/solidity/dpos_contract_interface.sol#L27C16-L27C38

**Comment by Malak67** [comment]
At the moment last commision change won`t help identifying new nodes. We are already using this property to check if the commission changed.
We would need a registeredAt property for each validator which we can get when we fetch each validator by address https://indexer.mainnet.explorer.taraxa.io/validators/0xf9d0eada55b9a3e8d9fd69dc3c57163c0d42dc18 
This will help in identifying new validators and not showing the commission change flag for new nodes and maybe for future features as well.
I talked with Matus and he will handle this.
