### ISSUE TITLE
Fix: Community site - Redeem - Claim requests

### ISSUE THREAD

**Issue by rattrap** [Taraxa-project/taraxa-platform#90]
There's a lot of confusion about the redeeming process.

<img width="1456" alt="Current" src="https://user-images.githubusercontent.com/3051409/156557781-3a747c74-5c8d-450d-bfbf-8d41a09ea08a.png">

The way it works right now is once you click the redeem button, we create a "claim request" that includes a secret hash that has to be sent to our [smart contract](https://github.com/Taraxa-project/tara-erc20/blob/main/contracts/Claim.sol) in order to claim your tokens.

If the user changes his mind and doesn't send that request to the blockchain (gas price too high), they can't keep earning points and claim all of them after some time as the UI shows.

So we need to:
1. show a list of all the claim requests with redeem buttons for each request
2. remove the general redeem button
3. show a warning on clicking a redeem button about this issue

<img width="1060" alt="Claim Requests" src="https://user-images.githubusercontent.com/3051409/156558636-1c2b88d6-73bd-443b-b8aa-d7b770627c22.png">

<img width="468" alt="Warning" src="https://user-images.githubusercontent.com/3051409/156558568-04479c3b-7b93-4bd8-b5c3-41782cfa89ba.png">

**Comment by VargaElod23** [comment]
Update: `develop` contains the visual fixes, but `/accounts/{address}` still returns 404 although there is backend data so that one still needs to be investigated.

**Comment by VargaElod23** [comment]
Unfortunately moving the endpoint didn't help @rattrap . I'll dig deeper tomorrow on why it has no data for my account...

**Comment by VargaElod23** [comment]
Hi @rattrap . The problem here comes from this https://github.com/Taraxa-project/taraxa-claim-backend/blob/ec7e9687359a01174a566d68e26f58a149e36b5c/src/modules/claim/claim.service.ts#L161 line. Can we discuss how the mapping is supposed to work here? TypeORM isn't creating any accounts table for this one.

**Comment by rattrap** [comment]
> Hi @rattrap . The problem here comes from this https://github.com/Taraxa-project/taraxa-claim-backend/blob/ec7e9687359a01174a566d68e26f58a149e36b5c/src/modules/claim/claim.service.ts#L161 line. Can we discuss how the mapping is supposed to work here? TypeORM isn't creating any accounts table for this one.

This just converts the entity to a JSON object so we can delete the id.

**Comment by rattrap** [comment]
@VargaElod23, found the problem.

With `esModuleInterop` turned on you have to replace:
```
import * as Claim from './contracts/Claim.json';
```
with
```
import Claim from './contracts/Claim.json';
```

The 404 was because we catch all exceptions in the controller and convert them to NotFound. We should also change that. Only throw a NotFound error if the exception is of type EntityNotFound.
